name: Test

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up environment
        uses: ./.github/actions/setup

      - name: Build project
        run: just build
        shell: bash

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: ./target/
          retention-days: 7

  # validate:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - name: Check out repository
  #       uses: actions/checkout@v4

  #     - name: Set up environment
  #       uses: ./.github/actions/setup

  #     - name: Download build artifacts
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: build-artifacts
  #         path: ./target/

  #     - name: Fix artifact permissions
  #       run: chmod +x ./target/stringspect

  #     - name: Validate Valgrind
  #       uses: Ximaz/valgrind-action@v1.2.0
  #       with:
  #         binary_path: "./target/stringspect"
  #         binary_args: "'test'"

  test:
    runs-on: ubuntu-latest
    # needs: validate
    needs: build
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up environment
        uses: ./.github/actions/setup

      - name: Run tests
        run: just test
        shell: bash
